version: '3'

services:
  backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    container_name: deploy
    environment:
      SPRING_DATASOURCE_URL: ${RDS_URL}
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
      naver.api.client.id: ${NAVER_API_CLIENT_ID}
      naver.api.client.secret: ${NAVER_API_CLIENT_SECRET}
    ports:
      - "8080:8080"
    restart: always
    networks:
      - omd

networks:
  omd:
    driver: bridge